<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_Nama BUKode BU</name>
   <tag></tag>
   <elementGuidId>1314abe1-f23c-461d-9401-33153447f486</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='opsiCariBU']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#opsiCariBU</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:label=&quot;Opsi Pencarian&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>f723ecd6-e8a7-45b5-a742-c864e3f80ad6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>opsiCariBU</value>
      <webElementGuid>85040994-46f9-457e-b72a-44c2d05f467b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>opsiCariBU</value>
      <webElementGuid>40fffdcc-8537-47b3-b9f4-b9fccdf8d76a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>4fb8f93e-e5c1-4f28-8923-b9518d1996b0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Nama BUKode BU</value>
      <webElementGuid>361a1fd1-0ddf-48ae-a5cf-f43d7e7eb2c1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;opsiCariBU&quot;)</value>
      <webElementGuid>5d53f548-97c5-4539-ae16-ce6c48b82f4f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='opsiCariBU']</value>
      <webElementGuid>1aa62e2e-9909-40d9-af5d-9763e3ae336f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='frmUsermodal']/div[2]/label/div/select</value>
      <webElementGuid>9a2e2e90-16f2-4cf0-968f-4ea56f806f1e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Pencarian Badan Usaha'])[1]/following::select[1]</value>
      <webElementGuid>89a91899-7e33-43f1-a139-9a4c95f35da3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='×'])[1]/following::select[1]</value>
      <webElementGuid>a6e89f00-3784-4f38-9556-91103688d1ee</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Opsi Pencarian'])[1]/preceding::select[1]</value>
      <webElementGuid>3cfd02a2-dddd-4eb2-b034-b2ed30b78f96</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Masukkan Kata Pencarian'])[1]/preceding::select[1]</value>
      <webElementGuid>b5d81ba5-045c-4bd7-9479-55ee594fe8f9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//label/div/select</value>
      <webElementGuid>f367ed86-925e-46e6-ad1d-ab7d08a59ab4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'opsiCariBU' and @name = 'opsiCariBU' and (text() = 'Nama BUKode BU' or . = 'Nama BUKode BU')]</value>
      <webElementGuid>f2277551-b720-49fc-a36c-f11469f0cf50</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
