<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_PatuhPatuh Dengan CatatanTidak Patuh</name>
   <tag></tag>
   <elementGuidId>a9cab650-b94f-4211-a0ae-b4db1c2e6fa6</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='swalJenis']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#swalJenis</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:label=&quot;PatuhPatuh Dengan CatatanTidak Patuh&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>350670b4-2962-4f35-905b-7e3bf0ef9de2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>swalJenis</value>
      <webElementGuid>dacd40d3-1ff9-4a53-88db-ea264cb34b11</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>swalJenis</value>
      <webElementGuid>ee16b10e-d1f6-486b-b131-2eb173c4b651</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>f335263b-4f13-455c-8cf6-d721ebbbd062</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>PatuhPatuh Dengan CatatanTidak Patuh</value>
      <webElementGuid>8cb5c09b-af94-4f5a-a4ff-91f9e6f310a7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;swalJenis&quot;)</value>
      <webElementGuid>9823ca0f-4f4c-4baa-9ce8-7475dbcd1286</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='swalJenis']</value>
      <webElementGuid>51358b07-d93c-4f56-87d5-0e34fe4a0853</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='frmUsermodal']/div[2]/label[2]/select</value>
      <webElementGuid>fccadf94-d281-4ca5-99ea-dcf0a71f9a16</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Kesimpulan'])[3]/following::select[1]</value>
      <webElementGuid>5842a809-d62c-4442-afee-3ea5df880ac9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Update Kesimpulan'])[1]/following::select[1]</value>
      <webElementGuid>77a975b7-820a-4f40-be41-5672828264c8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Catatan'])[1]/preceding::select[1]</value>
      <webElementGuid>876e4115-2fc6-4c90-bd2a-5f00c50bf67a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Simpan'])[1]/preceding::select[2]</value>
      <webElementGuid>e6b5f4f7-452f-4b27-a69d-f6d8a14cc1f2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/label[2]/select</value>
      <webElementGuid>d7b6fbd6-47d2-4131-bb70-d447658f7fed</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'swalJenis' and @name = 'swalJenis' and (text() = 'PatuhPatuh Dengan CatatanTidak Patuh' or . = 'PatuhPatuh Dengan CatatanTidak Patuh')]</value>
      <webElementGuid>a8cc3651-174f-42b0-ba48-d3af1fc04e18</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
