<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_Tolak</name>
   <tag></tag>
   <elementGuidId>244db4b9-3d67-49f1-8801-68f55fd986a7</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='aksi']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#aksi</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:label=&quot;Setuju \n                            Tolak&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>ed65d9bf-de57-485c-851a-21e8a3bb78e4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>aksi</value>
      <webElementGuid>48617817-9031-42ac-ac23-6ddb6c441870</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>aksi</value>
      <webElementGuid>061ae992-8ca0-44aa-b26e-ba39c4e89228</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>99b0cacc-a800-47cf-abd7-73040c7ca99a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
                            Setuju 
                            Tolak
                        </value>
      <webElementGuid>748feb40-5ab6-46d2-97c0-da8d4aefedf4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;aksi&quot;)</value>
      <webElementGuid>e56ab57b-abb6-46cc-86cf-82c58c62eaf4</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='aksi']</value>
      <webElementGuid>862f5c29-8c3a-42c3-b9d7-311b0cd30267</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='›'])[1]/following::select[1]</value>
      <webElementGuid>1fac1e8f-6cdb-497e-a96c-b779e4ca380f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='‹'])[1]/following::select[1]</value>
      <webElementGuid>d20caca0-d6de-47e4-8199-550e84a5523f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Copyright © BPJS Kesehatan.'])[1]/preceding::select[1]</value>
      <webElementGuid>42188b98-db65-4ed2-92b5-a9b313895e02</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//label[2]/label/select</value>
      <webElementGuid>69065e89-81fb-4fdf-a470-55b7c7dded20</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'aksi' and @name = 'aksi' and (text() = '
                            Setuju 
                            Tolak
                        ' or . = '
                            Setuju 
                            Tolak
                        ')]</value>
      <webElementGuid>b19f59e0-4f81-4ec1-a9cb-74299dffbc9b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
